#!/usr/bin/env bash
# A bash displays "Best School" 10 times using an until loop.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
