#!/usr/bin/env bash
# A bash that displays numbers from 1 to 20.

count=1

while [ $count -le 20 ]
do
  if [ $count -eq 4 ]
  then
    echo 4
    echo "bad luck from china"
  elif [ $count -eq 9 ]
  then
    echo "bad luck from japan
done
