#!/usr/bin/env bash
# A bash that displays numbers from 1 to 20.

count=1

while [ $count -le 20 ]
do
  echo '$count"
  case $count in
    "4") echo "bad luck from china";;
    "9") echo "bad luck from japan";;
    "17") echo "bad luck from italy";;
  esac
  (( count++ ))
done
