#!/usr/bin/env bash
# A bash script that displays
#   The content of the current directory.
#   In a list format
#   The part of the name after first dash.

list=$(ls)
for x in $list; do
  echo "$x" | cut -d '-' -f2
done
